---
- name: "Install bash-completion"
  package:
    pkg: "{{ install_bash_completion_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
    state: "present"
  tags:
    - "bash-completion"
